### ISSUE TITLE
Ceck Interface Name

### ISSUE THREAD

**Issue by m4rkh4ck** [synackid/netscanner#1]
Good job, this tool is very simple to use and works very well. I would put a check on the choice of interface. Specifically when I write the interface on which to scan and it should be wrong, it would be appropriate to immediately generate an error message.
![Immagine 2022-04-14 141607](https://user-images.githubusercontent.com/92309458/163388698-a14c61c8-d09f-4807-b169-b8a53b103005.png)

**Comment by synackid** [comment]
Thank you for the suggestions. I will start fixing it.

**Comment by synackid** [comment]
Check implemented, thank you.
